<?php

namespace app\components\web;

use app\widgets\Select2Default;

class ActiveField extends \yii\bootstrap4\ActiveField
{
    public function dropdownList2($config = [])
    {
        $this->enableLabel = false;
        return parent::widget(Select2Default::class, $config); // TODO: Change the autogenerated stub
    }
}